--------------------------------------------------------
--  File created - Friday-September-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYS"."EMPLOYEE" 
   (	"EMP_ID" NUMBER, 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER, 
	"DEPT_ID" NUMBER, 
	"HIRE_DATE" DATE, 
	"JOB_ID" VARCHAR2(50 BYTE), 
	"MANAGER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

/

SET DEFINE OFF;
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (100,'King',24000,90,to_date('17-JUN-03','DD-MON-RR'),'AD_PRES',null);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (101,'Kochhar',17000,90,to_date('21-SEP-05','DD-MON-RR'),'AD_VP',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (102,'De Haan',17000,90,to_date('13-JAN-01','DD-MON-RR'),'AD_VP',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (103,'Hunold',9000,60,to_date('03-JAN-06','DD-MON-RR'),'IT_PROG',102);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (104,'Ernst',6000,60,to_date('21-MAY-07','DD-MON-RR'),'IT_PROG',103);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (105,'Austin',4800,60,to_date('25-JUN-05','DD-MON-RR'),'IT_PROG',103);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (106,'Pataballa',4800,60,to_date('05-FEB-06','DD-MON-RR'),'IT_PROG',103);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (107,'Lorentz',4200,60,to_date('07-FEB-07','DD-MON-RR'),'IT_PROG',103);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (108,'Greenberg',12008,100,to_date('17-AUG-02','DD-MON-RR'),'FI_MGR',101);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (109,'Faviet',9000,100,to_date('16-AUG-02','DD-MON-RR'),'FI_ACCOUNT',108);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (110,'Chen',8200,100,to_date('28-SEP-05','DD-MON-RR'),'FI_ACCOUNT',108);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (111,'Sciarra',7700,100,to_date('30-SEP-05','DD-MON-RR'),'FI_ACCOUNT',108);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (112,'Urman',7800,100,to_date('07-MAR-06','DD-MON-RR'),'FI_ACCOUNT',108);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (113,'Popp',6900,100,to_date('07-DEC-07','DD-MON-RR'),'FI_ACCOUNT',108);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (114,'Raphaely',11000,30,to_date('07-DEC-02','DD-MON-RR'),'PU_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (115,'Khoo',3100,30,to_date('18-MAY-03','DD-MON-RR'),'PU_CLERK',114);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (116,'Baida',2900,30,to_date('24-DEC-05','DD-MON-RR'),'PU_CLERK',114);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (117,'Tobias',2800,30,to_date('24-JUL-05','DD-MON-RR'),'PU_CLERK',114);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (118,'Himuro',2600,30,to_date('15-NOV-06','DD-MON-RR'),'PU_CLERK',114);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (119,'Colmenares',2500,30,to_date('10-AUG-07','DD-MON-RR'),'PU_CLERK',114);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (120,'Weiss',8000,50,to_date('18-JUL-04','DD-MON-RR'),'ST_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (121,'Fripp',8200,50,to_date('10-APR-05','DD-MON-RR'),'ST_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (122,'Kaufling',7900,50,to_date('01-MAY-03','DD-MON-RR'),'ST_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (123,'Vollman',6500,50,to_date('10-OCT-05','DD-MON-RR'),'ST_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (124,'Mourgos',5800,50,to_date('16-NOV-07','DD-MON-RR'),'ST_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (125,'Nayer',3200,50,to_date('16-JUL-05','DD-MON-RR'),'ST_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (126,'Mikkilineni',2700,50,to_date('28-SEP-06','DD-MON-RR'),'ST_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (127,'Landry',2400,50,to_date('14-JAN-07','DD-MON-RR'),'ST_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (128,'Markle',2200,50,to_date('08-MAR-08','DD-MON-RR'),'ST_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (129,'Bissot',3300,50,to_date('20-AUG-05','DD-MON-RR'),'ST_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (130,'Atkinson',2800,50,to_date('30-OCT-05','DD-MON-RR'),'ST_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (131,'Marlow',2500,50,to_date('16-FEB-05','DD-MON-RR'),'ST_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (132,'Olson',2100,50,to_date('10-APR-07','DD-MON-RR'),'ST_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (133,'Mallin',3300,50,to_date('14-JUN-04','DD-MON-RR'),'ST_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (134,'Rogers',2900,50,to_date('26-AUG-06','DD-MON-RR'),'ST_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (135,'Gee',2400,50,to_date('12-DEC-07','DD-MON-RR'),'ST_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (136,'Philtanker',2200,50,to_date('06-FEB-08','DD-MON-RR'),'ST_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (137,'Ladwig',3600,50,to_date('14-JUL-03','DD-MON-RR'),'ST_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (138,'Stiles',3200,50,to_date('26-OCT-05','DD-MON-RR'),'ST_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (139,'Seo',2700,50,to_date('12-FEB-06','DD-MON-RR'),'ST_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (140,'Patel',2500,50,to_date('06-APR-06','DD-MON-RR'),'ST_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (141,'Rajs',3500,50,to_date('17-OCT-03','DD-MON-RR'),'ST_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (142,'Davies',3100,50,to_date('29-JAN-05','DD-MON-RR'),'ST_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (143,'Matos',2600,50,to_date('15-MAR-06','DD-MON-RR'),'ST_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (144,'Vargas',2500,50,to_date('09-JUL-06','DD-MON-RR'),'ST_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (145,'Russell',14000,80,to_date('01-OCT-04','DD-MON-RR'),'SA_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (146,'Partners',13500,80,to_date('05-JAN-05','DD-MON-RR'),'SA_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (147,'Errazuriz',12000,80,to_date('10-MAR-05','DD-MON-RR'),'SA_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (148,'Cambrault',11000,80,to_date('15-OCT-07','DD-MON-RR'),'SA_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (149,'Zlotkey',10500,80,to_date('29-JAN-08','DD-MON-RR'),'SA_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (150,'Tucker',10000,80,to_date('30-JAN-05','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (151,'Bernstein',9500,80,to_date('24-MAR-05','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (152,'Hall',9000,80,to_date('20-AUG-05','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (153,'Olsen',8000,80,to_date('30-MAR-06','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (154,'Cambrault',7500,80,to_date('09-DEC-06','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (155,'Tuvault',7000,80,to_date('23-NOV-07','DD-MON-RR'),'SA_REP',145);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (156,'King',10000,80,to_date('30-JAN-04','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (157,'Sully',9500,80,to_date('04-MAR-04','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (158,'McEwen',9000,80,to_date('01-AUG-04','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (159,'Smith',8000,80,to_date('10-MAR-05','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (160,'Doran',7500,80,to_date('15-DEC-05','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (161,'Sewall',7000,80,to_date('03-NOV-06','DD-MON-RR'),'SA_REP',146);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (162,'Vishney',10500,80,to_date('11-NOV-05','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (163,'Greene',9500,80,to_date('19-MAR-07','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (164,'Marvins',7200,80,to_date('24-JAN-08','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (165,'Lee',6800,80,to_date('23-FEB-08','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (166,'Ande',6400,80,to_date('24-MAR-08','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (167,'Banda',6200,80,to_date('21-APR-08','DD-MON-RR'),'SA_REP',147);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (168,'Ozer',11500,80,to_date('11-MAR-05','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (169,'Bloom',10000,80,to_date('23-MAR-06','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (170,'Fox',9600,80,to_date('24-JAN-06','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (171,'Smith',7400,80,to_date('23-FEB-07','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (172,'Bates',7300,80,to_date('24-MAR-07','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (173,'Kumar',6100,80,to_date('21-APR-08','DD-MON-RR'),'SA_REP',148);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (174,'Abel',11000,80,to_date('11-MAY-04','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (175,'Hutton',8800,80,to_date('19-MAR-05','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (176,'Taylor',8600,80,to_date('24-MAR-06','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (177,'Livingston',8400,80,to_date('23-APR-06','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (178,'Grant',7000,null,to_date('24-MAY-07','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (179,'Johnson',6200,80,to_date('04-JAN-08','DD-MON-RR'),'SA_REP',149);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (180,'Taylor',3200,50,to_date('24-JAN-06','DD-MON-RR'),'SH_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (181,'Fleaur',3100,50,to_date('23-FEB-06','DD-MON-RR'),'SH_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (182,'Sullivan',2500,50,to_date('21-JUN-07','DD-MON-RR'),'SH_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (183,'Geoni',2800,50,to_date('03-FEB-08','DD-MON-RR'),'SH_CLERK',120);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (184,'Sarchand',4200,50,to_date('27-JAN-04','DD-MON-RR'),'SH_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (185,'Bull',4100,50,to_date('20-FEB-05','DD-MON-RR'),'SH_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (186,'Dellinger',3400,50,to_date('24-JUN-06','DD-MON-RR'),'SH_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (187,'Cabrio',3000,50,to_date('07-FEB-07','DD-MON-RR'),'SH_CLERK',121);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (188,'Chung',3800,50,to_date('14-JUN-05','DD-MON-RR'),'SH_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (189,'Dilly',3600,50,to_date('13-AUG-05','DD-MON-RR'),'SH_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (190,'Gates',2900,50,to_date('11-JUL-06','DD-MON-RR'),'SH_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (191,'Perkins',2500,50,to_date('19-DEC-07','DD-MON-RR'),'SH_CLERK',122);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (192,'Bell',4000,50,to_date('04-FEB-04','DD-MON-RR'),'SH_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (193,'Everett',3900,50,to_date('03-MAR-05','DD-MON-RR'),'SH_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (194,'McCain',3200,50,to_date('01-JUL-06','DD-MON-RR'),'SH_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (195,'Jones',2800,50,to_date('17-MAR-07','DD-MON-RR'),'SH_CLERK',123);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (196,'Walsh',3100,50,to_date('24-APR-06','DD-MON-RR'),'SH_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (197,'Feeney',3000,50,to_date('23-MAY-06','DD-MON-RR'),'SH_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (198,'OConnell',2600,50,to_date('21-JUN-07','DD-MON-RR'),'SH_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (199,'Grant',2600,50,to_date('13-JAN-08','DD-MON-RR'),'SH_CLERK',124);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (200,'Whalen',4400,10,to_date('17-SEP-03','DD-MON-RR'),'AD_ASST',101);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (201,'Hartstein',13000,20,to_date('17-FEB-04','DD-MON-RR'),'MK_MAN',100);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (202,'Fay',6000,20,to_date('17-AUG-05','DD-MON-RR'),'MK_REP',201);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (203,'Mavris',6500,40,to_date('07-JUN-02','DD-MON-RR'),'HR_REP',101);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (204,'Baer',10000,70,to_date('07-JUN-02','DD-MON-RR'),'PR_REP',101);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (205,'Higgins',12008,110,to_date('07-JUN-02','DD-MON-RR'),'AC_MGR',101);
Insert into EMPLOYEE (EMP_ID,LAST_NAME,SALARY,DEPT_ID,HIRE_DATE,JOB_ID,MANAGER_ID) values (206,'Gietz',8300,110,to_date('07-JUN-02','DD-MON-RR'),'AC_ACCOUNT',205);
commit;